name: CI Backend
on:
  push: { branches: ["**"] }
  pull_request:
jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ matrix.python-version }} }
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('backend/requirements*.txt') }}
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r backend/requirements.txt
          pip install -r backend/requirements-dev.txt
      - name: Lint (ruff)
        run: python -m ruff check backend
      - name: Typecheck (mypy)
        run: python -m mypy backend
      - name: Tests
        run: |
          cd backend
          pytest -q --cov=backend --cov-report=xml
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage.xml

